/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void exit_click(GButton source, GEvent event) { //_CODE_:exit_button:341278:
  //println("button1 - GButton >> GEvent." + event + " @ " + millis());
  exit();
} //_CODE_:exit_button:341278:

public void randombc_click(GButton source, GEvent event) { //_CODE_:random_button:242941:
  //println("random_button - GButton >> GEvent." + event + " @ " + millis());
  int r1 = int(random(0,255));
  int r2 = int(random(0,255));
  int r3 = int(random(0,255));
  
  color temp = color(r1, r2, r3);
  
  background(temp);
} //_CODE_:random_button:242941:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  label1 = new GLabel(this, 112, 22, 160, 40);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Projeto Teste");
  label1.setOpaque(false);
  exit_button = new GButton(this, 144, 573, 80, 30);
  exit_button.setText("Exit");
  exit_button.addEventHandler(this, "exit_click");
  random_button = new GButton(this, 142, 534, 80, 30);
  random_button.setText("Random Color");
  random_button.addEventHandler(this, "randombc_click");
}

// Variable declarations 
// autogenerated do not edit
GLabel label1; 
GButton exit_button; 
GButton random_button; 
