package processing.test.projetoec;

/* autogenerated by Processing revision 1293 on 2023-10-11 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class ProjetoEC extends PApplet {

//Arquivo Principal

//Defines
boolean debugMode = false;

//UI Graphics
PImage background;
ClickArea[] loadedAreas;
SceneBehaviour currentBehaviour;

public void setup(){
  /* size commented out by preprocessor */;
  PrintMainMenu();
}

public void draw(){
  if(currentBehaviour != null){
    currentBehaviour.Update();
  }
}

public void mouseClicked(){
  CheckForTap();
}

public void CheckForTap(){
  //Check if the tap was inside any active loaded area
  if(debugMode){
    print("\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
    print("x:" + mouseX + '\n');
    print("y:" + mouseY + '\n');
  }
  
  if(loadedAreas.length > 0 ){
    for(int i = 0; i < loadedAreas.length; i++){
      if(mouseX > loadedAreas[i].topLeftX && mouseX < loadedAreas[i].bottomRightX){
          if(mouseY > loadedAreas[i].topLeftY && mouseY < loadedAreas[i].bottomRightY){
            loadedAreas[i].storedCommand.OnClick();
            //print("Called!");
          }
      }
    }
  }
}
//Use this file to define and extend command calls.
//I should probably have done lambdas instead of inheritance for this

public class OnClickCommand {
  public void OnClick(){}
}

//Return to Main Menu
public class OnClickCommandOpenMainMenu extends OnClickCommand{
  public void OnClick(){
    PrintMainMenu();
  }
}

//Open Content Menu
public class OnClickCommandOpenContent extends OnClickCommand{
  public void OnClick(){
    PrintContentPage();
  }
}
//Use this file to define variables.

//Global Static
final float appVersion = 1.0f; //<-- current version of the app

//Global Settings
boolean saveStats = true;
boolean music = true;
boolean soundEffects = true;
int secondsPerQuestion = 30;

//Global Data
int rights = 0; //<--- number of question gotten right ever since starting using the program
int wrongs = 0; //<--- number of question gotten wrong ever since starting using the program
//Use this file to build scenes

//Call this function every time a scene is loaded for house keeping.
public void PrintSceneBase(){
  currentBehaviour = null;
}

//Print Main Menu to Screen
public void PrintMainMenu(){
  //Load Images
  background = loadImage("mainmenu.png");
  
  //Main Menu
  background(165,165,255);
  image(background, 0, 0, width, height);
  
  //Extra Behaviour
  currentBehaviour = null;
  
  //Assign
  loadedAreas = new ClickArea[1];
  loadedAreas[0] = new ClickArea(50,250,380,330, new OnClickCommandOpenContent());
}

public void PrintContentPage(){
  //Load Images
  background = loadImage("content.png");
  
  //Main Menu
  background(165,165,255);
  image(background, 0, 0, width, height);
  
  //Extra Behaviour
  currentBehaviour = null;
  
  //Assign
  loadedAreas = new ClickArea[1];
  loadedAreas[0] = new ClickArea(15,15,85,75, new OnClickCommandOpenMainMenu()); //Return to main menu
}
//Use this file to declare data structures.

//Describes an area of the canvas that is clickable.
public class ClickArea{
  //Pos
  int topLeftX, topLeftY; //Trigger area click position
  int bottomRightX, bottomRightY; //Trigger area click position
  public OnClickCommand storedCommand = null; //Effect from click
  
  public ClickArea(int x1, int y1, int x2,int y2, OnClickCommand command){
    topLeftX = x1;
    topLeftY = y1;
    bottomRightX = x2;
    bottomRightY = y2;
    storedCommand = command;
  }
}

//Describes a Special behaviour from a specific scene
public class SceneBehaviour{
  public void Update(){}
}

public class QuizBehaviour extends SceneBehaviour{
  public void Update(){
    
  }
}


  public void settings() { size(450, 800); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "ProjetoEC" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
